### ISSUE TITLE
Disable Captcha?

### ISSUE THREAD

**Issue by DracoMilesX** [darkshifty/rpg#2]
Trying to set this up and now register an account but for some reason the captcha isn't working. I eneterd the site and secret key. Had to place site key on line 446 instead of 381 guess readme is just outdated? And I adjusted the line and removed the <?= ?> part since that threw an error. For secret key I added the ' at both ends. 

So is their any way to disable the captcha for now?

**Comment by DracoMilesX** [comment]
Well this can be closed appears to be working under chrome but not under firefox.

**Comment by darkshifty** [comment]
It works in both browsers, if you set the keys properly (check out pokeworld.nl).

**Comment by DracoMilesX** [comment]
Think it might be related to the fact that I use FireFox Nightly then since pokeworld.nl doesn't work for me as well in private mode without extension and in normal mode with extension disabled.
