### ISSUE TITLE
General error: 1364 Field 'ip_ingelogd' doesn't have a default value in

### ISSUE THREAD

**Issue by DracoMilesX** [darkshifty/rpg#3]
Trying to register an account I receive the following error, tested with pokeworld.nl site itself and their it does work.

Warning: PDOStatement::execute(): SQLSTATE[HY000]: General error: 1364 Field 'ip_ingelogd' doesn't have a default value in /web/pokemonrpg/register.php on line 160
Warning: PDOStatement::execute(): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' in /web/pokemonrpg/register.php on line 169
Warning: Cannot modify header information - headers already sent by (output started at /web/pokemonrpg/index.php:543) in /web/pokemonrpg/register.php on line 267

**Comment by Nkallianz** [comment]
Everybody is banned but table ban is empty. I create new user and don't receive confirmation email and the user is blocked

**Comment by Nkallianz** [comment]
Warning: PDOStatement::execute(): SQLSTATE[HY000]: General error: 1364 Field 'ip_ingelogd' doesn't have a default value in /web/pokemonrpg/register.php on line 160

You need to set a default value to field ip_ingelogd.


Warning: PDOStatement::execute(): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' in /web/pokemonrpg/register.php on line 169

You need to change duplicated primary key

**Comment by darkshifty** [comment]
@DracoMilesX, it depends on your sql mode. It seems that you have it set to strict.

**Comment by DracoMilesX** [comment]
@darkshifty Thanks for the information. The Database errors are gone now I have only this one remaining:

﻿ Warning: Cannot modify header information - headers already sent by (output started at /volume4/web/pokemonrpg/index.php:543) in /web/pokemonrpg/register.php on line 267

**Comment by Nkallianz** [comment]
@DracoMilesX  Usually this error 

> Fatal error: Uncaught Error: Call to undefined function mysql_fetch_assoc() in 

 happed because sql sintaxe, but try to change this to PDO or Mysqli, mysql's sintax are deprecated.

**Comment by DracoMilesX** [comment]
@Nkallianz Thanks for the info but then it is better to update the source in the github repo and make it mysqli or PDO instead of mysql.

**Comment by Nkallianz** [comment]
So, we can work together! 😄

**Comment by darkshifty** [comment]
The source is slowly beeing converted to PHP7, for now it supports PHP5.6 and lower. This issue is resolved.
