### ISSUE TITLE
Homepage login redirects to website ip instead of ip/rpg

### ISSUE THREAD

**Issue by DracoMilesX** [darkshifty/rpg#5]
As title stated when registering an account it all goes fine but when you try to login afterwards from the homepage it tries to continue to 192.168.1.1 instead of 192.168.1.1/rpg

edit:appears it happens with the login box in general.

**Comment by darkshifty** [comment]
Please check your settings if you are using a subfolder.

**Comment by DracoMilesX** [comment]
Pretty certain it has nothing to do with my settings. But with hardcoded lines in the source.

After modifying index.php in the root

Line 530 for the logo redirect: <a href="?page=home"><img src="<?=GLOBALDEF_SITELOGO?>" alt="" width="170px" /></a>
Removed the / at ?page=home

Line 972 same thing remove the / at the action="?page=home"

And under includes/login.php line 115 needs the / removed as well infront of index.php

**Comment by darkshifty** [comment]
Your absolutely right, thank you. I will fix it as soon as possible.
