### ISSUE TITLE
Issue with language or globaldef

### ISSUE THREAD

**Issue by pokemasterady** [darkshifty/rpg#7]
![screenshot_20181107-065807](https://user-images.githubusercontent.com/44824380/48105513-e238a880-e25d-11e8-9c67-1f5f9ac389e2.png)

Can you please help language is still not turning to english please help

**Comment by darkshifty** [comment]
You need to remove the cache after changing the language

**Comment by pokemasterady** [comment]
I upload the cache folder again still issue not solved

**Comment by pokemasterady** [comment]
Can you please specify what I should do .

Connection with db is fine.
Only issue I'm facing is language is not English on website prs.epizy.com  

Note: I reupload cache still not working

**Comment by darkshifty** [comment]
Empty the cache folder and check if globaldefs is beeing written check if GLOBALDEF_LANGUAGE contains the right value

**Comment by pokemasterady** [comment]
[globaldefs.php.txt](https://github.com/darkshifty/rpg/files/2558491/globaldefs.php.txt)

This is what is written in cache folder 's globaldefs.php

**Comment by pokemasterady** [comment]
This is screenshot of my cache folder
![img_20181107_231151_643](https://user-images.githubusercontent.com/44824380/48149633-a136a780-e2e2-11e8-9749-dd8a5d2e855d.JPG)

**Comment by pokemasterady** [comment]
Recaptcha is also not working

**Comment by darkshifty** [comment]
I just did a fresh install, everything(including recaptcha) is working. Make sure you follow the manual.

https://test.pokeworld.nl

**Comment by pokemasterady** [comment]
See language is still not changed
